version: '3.8'

services: 
  web-api:
      build: 
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 8015:8000
      command: uvicorn app.main:app --host 0.0.0.0 --reload
      volumes:
        - .:/app
      